{{- if and .Values.mysql.enabled (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-batch.mysql.secretName" . }}
  labels:
    {{- include "k8s-batch.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
type: Opaque
data:
  root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  username: {{ .Values.mysql.auth.username | b64enc | quote }}
  password: {{ .Values.mysql.auth.password | b64enc | quote }}
{{- end }}
