{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-batch.mysql.host" . }}
  labels:
    {{- include "k8s-batch.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: mysql
  selector:
    {{- include "k8s-batch.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }}
