{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "k8s-batch.fullname" . }}-mysql
  labels:
    {{- include "k8s-batch.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  serviceName: {{ include "k8s-batch.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-batch.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        {{- include "k8s-batch.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s-batch.mysql.secretName" . }}
                  key: root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.auth.database | quote }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s-batch.mysql.secretName" . }}
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s-batch.mysql.secretName" . }}
                  key: password
            - name: MYSQL_CHARACTER_SET_SERVER
              value: {{ .Values.mysql.config.mysqlCharacterSetServer | quote }}
            - name: MYSQL_COLLATION_SERVER
              value: {{ .Values.mysql.config.mysqlCollationServer | quote }}
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          startupProbe:
            {{- toYaml .Values.mysql.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.mysql.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.mysql.readinessProbe | nindent 12 }}
      volumes:
        - name: init-scripts
          configMap:
            name: {{ include "k8s-batch.fullname" . }}-mysql-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.mysql.persistence.accessModes | nindent 10 }}
        {{- if .Values.mysql.persistence.storageClass }}
        storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}
{{- end }}
