{{- if and .Values.gatewayHpa.enabled .Values.gateway.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "k8s-batch.fullname" . }}-gateway
  labels:
    {{- include "k8s-batch.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "k8s-batch.fullname" . }}-gateway
  minReplicas: {{ .Values.gatewayHpa.minReplicas }}
  maxReplicas: {{ .Values.gatewayHpa.maxReplicas }}
  metrics:
    {{- toYaml .Values.gatewayHpa.metrics | nindent 4 }}
  {{- with .Values.gatewayHpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
