{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-batch.fullname" . }}-gateway
  labels:
    {{- include "k8s-batch.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
  selector:
    {{- include "k8s-batch.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
{{- end }}
